### ISSUE TITLE
sample server.json

### ISSUE THREAD

**Issue by wga22** [stevedenman/plexamp-pi-zero#1]
Could someone please share sample server.json (token can be removed).  I dont seem to have one on my windows plexamp install, thus setting up headless on RPI has hit block.

Thank you!

**Comment by stephdenman** [comment]
Hi, this is the structure of the one I'm using;

```json
{
  "player": {
    "name": "<MACHINE-NAME>",
    "identifier": "<GUID>"
  },
  "user": {
    "id": <USER-ID>,
    "token": "<TOKEN>"
  }
}
```

**Comment by wga22** [comment]
thank you!  I hit a wall, and found link to the old windows plexamp (which still used server.json, 3.0 and higher doesnt).

Anyway, for others needing same help, here is what mine looks like:



{
  "player": {
    "name": "rpi",
    "identifier": "11bdb083-c715-4382-8feb-xxxxxxxxxxxx"
  },
  "user": {
    "id": 152XXXX,
    "token": "zCa2Ue-xxxxxxxxx"
  },
  "server": {
    "identifier": "82ac6c8ac64cd9fa9626fxxxxxxxxxxxx"
  },
  "state": {
    "source": "82ac6c7ac64cd9fa9626f15adb169c5631a0621f",
    "state": "playing",
    "time": 10101,
    "volume": 100,
    "playQueueID": 3420,
    "playQueueItemID": 94643
  }
}
